### ISSUE TITLE
add option 5) Ver inventario in main menu

### ISSUE THREAD

**Issue by Japoivvb** [05akaliyev/Recuperacion-UF5#1]
1. add new option in main menu, click on it or typing 5 a new window must appear with data loaded in inventory as show in below picture

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

![image](https://github.com/05akaliyev/Recuperacion-UF5/assets/36648472/90f08c3b-e48d-434d-82b4-b0ddbbb968d9)

**Comment by 05akaliyev** [comment]
![2024-06-03_23-45-53](https://github.com/05akaliyev/Recuperacion-UF5/assets/167184773/b672b8ba-5724-4cb5-8acc-d7f847d4d01f)
